### ISSUE TITLE
centos 版本的部署教程有吗

### ISSUE THREAD

**Issue by Blackcatfish** [ChainSQL/chainsqld#121]

**Comment by luleigreat** [comment]
参考Wiki里面的教程就可以，那个只是以ubuntu为例，centos部署几乎没有差别

**Comment by Blackcatfish** [comment]
执行脚本 出现system not supported

**Comment by Blackcatfish** [comment]
redhat也是一样

**Comment by Blackcatfish** [comment]
将可执行程序与配置文件（如chainsqld-example.cfg）放在用户目录，先启动一下：
nohup ./chainsqld --conf="./chainsqld-example.cfg"&  可执行程序怎么安装

**Comment by Blackcatfish** [comment]
大佬可以加微信吗 ny216021

**Comment by luleigreat** [comment]
系统版本要求：Ubuntu 14.04+、CentOS 6.5+、RedHat 7.0 +
