### ISSUE TITLE
节点之间不连接

### ISSUE THREAD

**Issue by Y2Nk4** [ChainSQL/chainsqld#146]
已经在配置文件里设置了
ips, validators, validation_seed, validation_public_key
节点都能正常启动，但是节点之间就是不连接。
节点间用telnet检测peer端口可以连通

是因为什么配置错了吗

**Comment by luleigreat** [comment]
是公网还是局域网，局域网的话，服务器时间都一致才行

**Comment by Y2Nk4** [comment]
是局域网，但是检查过了，服务器时间都一致
![TIM截图20191218014332.png](https://i.loli.net/2019/12/18/Jds8R7LmZbDrPpy.png)

**Comment by Y2Nk4** [comment]
一共四台服务器，时间都一致

**Comment by Y2Nk4** [comment]
这是配置文件
`
############################################################################################
###
### 这是一个单点启动的配置文件（自己作为验证节点），只做测试使用，真正运行时不会使用单点验证
### 查看具体配置说明请看https://github.com/ChainSQL/chainsqld/blob/master/doc/chainsqld-example.cfg
### 及 https://github.com/ChainSQL/chainsqld/blob/master/doc/ChainSQLDesign.md
###
############################################################################################

#端口配置列表
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

#http端口配置
[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 127.0.0.1
protocol = http

#peer端口配置，用于p2p节点发现
[port_peer]
port = 5129
ip = 0.0.0.0
protocol = peer

#websocket端口配置
[port_ws_admin_local]
port = 6006
ip = 0.0.0.0
admin = 127.0.0.1
protocol = ws


#-------------------------------------------------------------------------------

[node_size]
medium

# This is primary persistent datastore for rippled.  This includes transaction
# metadata, account states, and ledger headers.  Helpful information can be
# found here: https://ripple.com/wiki/NodeBackEnd
# delete old ledgers while maintaining at least 2000. Do not require an
# external administrative command to initiate deletion.
# 区块数据存储配置，windows下用NuDB,Linux/Mac下用RocksDB
[node_db]
type=RocksDB
path=./rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2

#是否全节点
[ledger_history]
full

#sqlite数据库（存储区块头数据，交易概要数据）
[database_path]
./db

# This needs to be an absolute directory reference, not a relative one.
# Modify this value as required.
[debug_logfile]
./debug.log

#时间服务器，用于不同节点单时间同步
[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

# Where to find some other servers speaking the Ripple protocol.
# 2016-12-15 15:00:00
# 要连接的其它节点的Ip及端口
[ips_fixed]
ip1 5126
ip2 5127
ip3 5128


# Public keys of the validators that this rippled instance trusts.
# 信任节点列表（信任节点的公钥列表）
[validators]
n9KaXRhFmCqXYjA8hrNG1s78V1uzBek3ZDFodx3pGWegFoqiZfKR
n9L58Mx9DznxPdrELsgpj33Xarxt6HbkAmv8Fc3Amdt4XWjmKkhf
n94hZy9Bu1BvU1RRH7mRZ54Ck9y61EMKT2vFDZRYy1pdjecgsLmi

# 本节点私钥（如不配置，不参与共识）
[validation_seed]
xnho1LAGkL6cuSQNJtWS3YQuLdb8u

# 本节点公钥
[validation_public_key]
n9KeQLrZ6xPDd1QBSEkYAjVAvh8T3dv2kZVKD7brhVvSjnFg2gaN

# Turn down default logging to save disk space in the long run.
#Valid values here are trace, debug, info, warning, error, and fatal
#日志级别，一般设置为warning级别
[rpc_startup]
{ "command": "log_level", "severity": "warning" }

# If ssl_verify is 1, certificates will be validated.
# To allow the use of self-signed certificates for development or internal use,
# set to ssl_verify to 0.
[ssl_verify]
0

#禁用某些支持但未不需要启用的特性
[veto_amendments]
42EEA5E28A97824821D4EF97081FE36A54E9593C6E4F20CBAE098C69D2E072DC fix1373
740352F2412A9909880C23A559FCECEDA3BE2126FED62FC7660D628A06927F11 Flow
E2E6F2866106419B88C50045ACE96368558C345566AC8F2BDF5A5B5587F0E6FA fix1368
C6970A8B603D8778783B61C0D445C23D1633CCFAEF0D43E7DBCD1521D34BD7C3 SHAMapV2
C1B8D934087225F509BEB5A8EC24447854713EE447D277F69545ABFA0E0FD490 Tickets
86E83A7D2ECE3AD5FA87AB2195AE015C950469ABF0B72EAACED318F74886AE90 CryptoConditionsSuite
1562511F573A19AE9BD103B5D6B9E01B3B46805AEC5D3C4805C902B514399146 CryptoConditions
3012E8230864E95A58C60FD61430D7E1B4D3353195F2981DC12B0C7C0950FFAC FlowCross


#chainsql数据库配置，根据自己的机子
#[sync_db]
#type=mysql
#host=localhost
#port=3306
#user=root
#pass=root
#db=chainsql
#first_storage=0
#charset=utf8
#unix_socket=/var/lib/mysql/mysql.sock

# 开户自动同步后，节点运行情况下会去自动同步新建的表，开启这个开关，或者使用sync_tables标签的配置，否则无法同步表
#[auto_sync]
#0
`

**Comment by luleigreat** [comment]
首页最下方有加微信群的方式，进群说吧

**Comment by Y2Nk4** [comment]
解决了，ChainSQL技术推荐尝试把DB和rocksdb删了重新启动，db有缓存会影响节点发现
