### ISSUE TITLE
db_noDbConfig

### ISSUE THREAD

**Issue by yiruacm** [ChainSQL/chainsqld#149]
系统是ubuntu16.04，mysql是5.7.31，数据库在本地和远程都能正常连接使用。
sync_db的配置信息如下
`[sync_db]
type=mysql
host=127.0.0.1
port=3306
user=root
pass=root
db=chainsql
first_storage=0
charset=utf8
`
socket连接显示成功，但是使用createTable创建数据表一直报错“db_noDbConfig”，这个要怎么解决呢？

**Comment by luleigreat** [comment]
已在微信群解决
