### ISSUE TITLE
balance decrease unexpectedly

### ISSUE THREAD

**Issue by Gordon-H** [ChainSQL/chainsqld#18]
I created an account and pay it 1000. Then I used that account to insert a new record into a table, but I found the balance of that account decrease to 999 unexpectedly. 
------
updated on Feb.12
I think it's because a transaction cost some fee, right? Is there any way to control the amount of fee?

**Comment by luleigreat** [comment]
Yes, every transaction in chainsql will cost some fee, the detail rule of table-operation related fee can be found in https://github.com/ChainSQL/chainsqld/blob/develop/doc/ChainsqlBase.md ,in the third section.

**Comment by luleigreat** [comment]
The rule of fee cannot be configured now,if you want to make it configurable, you can create a new branch and change the code, it's our pleasure to see new pull request for improvement.
