### ISSUE TITLE
chainsql account problem

### ISSUE THREAD

**Issue by Gordon-H** [ChainSQL/chainsqld#3]
按照文档搭建了chainsql网络，在account上遇到了问题。我用Java API的generateAddress生成地址，然后再使用该地址查询，总会有Account not found的错误。换成在chainsqld.cfg中配置的seed，也是一样的结果。这里的account应该怎样生成？我要创建表的话要用什么account？

**Comment by luleigreat** [comment]
新生成的地址在链上是不存在的，需要用一个有钱的账户给它打钱激活，参考 pay接口，链的根账户地址是
{ "address":"zHb9CJAWyB4zj91VRWn96DkukG4bwdtyTh","secret":"xnoPBzXtMeMyMHUVTgbuqAfg1SUTb"}，链初始时，这个地址上有所有的众享币

**Comment by Blackcatfish** [comment]
你是怎么把链搭起来的  设么系统Ubuntu  还是centos
