### ISSUE TITLE
grant didn't work

### ISSUE THREAD

**Issue by Gordon-H** [ChainSQL/chainsqld#9]
使用Java SDK，根用户创建了表，然后执行：
`JSONObject obj = c.grant("users", addressA,
                "{insert:true, select:true, delete:true, update:true}")
                .submit(Submit.SyncCond.validate_success);`
来授权，然后use(addressA), as(addressA, secretA), 执行get查询，总是返回：
{"error_message":"can't get TableName in DB ,please check field tablename!","status":"error"}

**Comment by peersafe** [comment]
You should not use addressA, it should be the original owner of the table.

**Comment by luleigreat** [comment]
use指定表的创建者
as指定当前操作用户，你这里use的参数应该传表的创建者
