### ISSUE TITLE
Not able to create table and identify source address

### ISSUE THREAD

**Issue by ahbharadwaj** [ChainSQL/chainsqld#96]
Chainsql  c= Chainsql .c;
         c. connect ( "ws://127.0.0.1:6006" );
         System.out.println("successfully connected to chainsql");

c.as("n94ngNasveyfF2KttLuNni6nHPcUtw1Se3969nUginy8cf2Kzb4Z", "xnoPBzXtMeMyMHUVTgbuqAfg1SUTb"); 
         
c. createTable ( "dc_universe" , c. array ( 
"{'field':'id','type':'int','length':11,'PK':1,'NN':1 , 'UQ':1}" , 
"{'field':'name','type':'varchar','length':50,'default':null}" , 
"{'field':'age' , 'type': 'int'}" ),
FALSE)
. submit (SyncCond.db_success);
         
Ouput:
Nov 05, 2018 1:23:48 PM com.peersafe.base.client.Client log
INFO: Connecting to ws://127.0.0.1:6006
connect success
successfully connected to chainsql
Account is missing,please checkout!
Exception: Owner or User parse failed

I don't understand where to find the address and how to create a table with owner account.
Any guidance on this will be really helpful.

Thanks,
Ananth

**Comment by ahbharadwaj** [comment]
Could please someone reply on this issue? I have a small project depending on this and I will be not able to proceed further until I resolve this issue.

**Comment by luleigreat** [comment]
In you code 
`c.as("n94ngNasveyfF2KttLuNni6nHPcUtw1Se3969nUginy8cf2Kzb4Z", "xnoPBzXtMeMyMHUVTgbuqAfg1SUTb");`
the first argument should be an address generated by api 'generateAddress', you give an adress generated by 'validationCreate'. It's not a valid account address.

**Comment by ahbharadwaj** [comment]
But again it takes me to same error even if I obtain and secret key from the generateAddress() Api

   Chainsql  c= Chainsql.c;
         c. connect ( "ws://127.0.0.1:6006" );
         c.getLedger();
         System.out.println("successfully connected to chainsql");
      
         JSONObject json = c.generateAddress();
         String address="";
         String secret="";
  
     
for(Iterator iterator = json.keySet().iterator(); iterator.hasNext();) {
    String key = (String) iterator.next();
   System.out.println(json.get(key));
        //System.out.println(json.getString("address"));
        address=json.getString("address");
        secret=json.getString("secret");
}


c.as(address, secret);   
System.out.println(address);
c. createTable ( "dc_universe" , c. array ( 
"{'field':'id','type':'int','length':11,'PK':1,'NN':1 , 'UQ':1}" , 
"{'field':'name','type':'varchar','length':50,'default':null}" , 
"{'field':'age' , 'type': 'int'}" ),
FALSE)
. submit (SyncCond.db_success);

run:
Nov 06, 2018 2:15:36 AM com.peersafe.base.client.Client log
INFO: Connecting to ws://127.0.0.1:6006
connect success
successfully connected to chainsql

zDyBNivcXTJhRF1FzqHZ4V6PjFZGd7U2GY
Can not find validated ledger!

**Comment by luleigreat** [comment]
Your chain is not valid, you view deploy wiki
